# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# pylint needs to be run in the local venv (vs pre-commit's generated) so imports work
# - should be installed via `pip install -r requirements-dev.txt`

repos:
-   repo: meta
    hooks:
    -   id: identity
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
    -   id: black
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.9.1
#     hooks:
#     - id: flake8
# r1
# -   repo: https://github.com/aerickson/urlchecker-python
#     rev: 155323e9cade3c9918564147bf826c604c4a7ffb
#     hooks:
#     - id: urlchecker
# r2
-   repo: https://github.com/aerickson/urlchecker-python
    rev: c5a7107a07bf7a8851924704e06edfbcf9b57f35
    hooks:
    -   id: urlchecker
