# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# pylint needs to be run in the local venv (vs pre-commit's generated) so imports work
# - should be installed via `pip install -r requirements-dev.txt`

repos:
-   repo: meta
    hooks:
    -   id: identity
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
    -   id: black
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.9.1
#     hooks:
#     - id: flake8
# r1
# -   repo: https://github.com/aerickson/urlchecker-python
#     rev: 155323e9cade3c9918564147bf826c604c4a7ffb
#     hooks:
#     - id: urlchecker
# r2
# r3 now
-   repo: https://github.com/aerickson/urlchecker-python
    rev: 88549367e9a99013d46635df5c697e2d2ad85670
    hooks:
    -   id: urlchecker
        # below are optional. override the config in the repo
        entry: urlchecker check_ci --exclude-pattern "http://excluded_domain.faah"
        types_or: [markdown, json]
        exclude: |
          (?x)^(
              version.json|
              package.json|
              package-lock.json|
              ^tests/.*|
              ^node_modules/.*
          )$
